# 2.1 Data Manipulations

In [3]:
# Import Pytorch library
import torch

In [227]:
if torch.cuda.is_available():
    device = "cuda" 
elif torch.backends.mps.is_available():
    device="mps"
else:
    device = "cpu"

## Torch Datatypes
PyTorch has twelve different data types:
| Data Type                 | dtype                                         | 
| ---                       | ---                                           |
| 32 bit floating point     | ```torch.float32``` or ```torch.float```      |
| 64 bit floating point     | ```torch.float64``` or ```torch.double```     |
| 64 bit Complex            | ```torch.complex64``` or ```torch.cfloat```   |
| 128 bit complex           | ```torch.complex128``` or ```torch.cdouble``` |
| 16 bit float point 1      | ```torch.float16``` or ```torch.half```       |
| 16 bit float point 2      | ```torch.bfloat16```                          |
| 8 bit Integer (Unsigned)  | ```torch.uint8```                             |
| 8 bit Integer (signed)    | ```torch.int8```                              |
| 16 bit Integer (signed)   | ```torch.int16``` or ```torch.short```        |
| 32 bit Integer (signed)   | ```torch.int32``` or ```torch.int```          |
| 64 bit Integer (signed)   | ```torch.int64``` or ```torch.long```         |
| Boolean                   | ```torch.bool```                              |



A ```python torch.dtype``` is an object that represents the data type of a ```python torch.Tensor```.

In [8]:
float_tensor = torch.ones(1, dtype=torch.float)
double_tensor = torch.ones(1, dtype=torch.double)
complex_float_tensor = torch.ones(1, dtype=torch.complex64)
complex_double_tensor = torch.ones(1, dtype=torch.complex128)
int_tensor = torch.ones(1, dtype=torch.int)
long_tensor = torch.ones(1, dtype=torch.long)
uint_tensor = torch.ones(1, dtype=torch.uint8)
double_tensor = torch.ones(1, dtype=torch.double)
bool_tensor = torch.ones(1, dtype=torch.bool)
# zero-dim tensors
long_zerodim = torch.tensor(1, dtype=torch.long)
int_zerodim = torch.tensor(1, dtype=torch.int)

## Tensors (N-dimensionsal arrays)

- A tensor represents a (possibly multidimensional) array of numerical values.
- one-dimensional case, i.e., when only one axis is needed for the data, a tensor is called a vector.
- With two axes, a tensor is called a matrix
- with $ n \gt 2 $:  ${n}^{th}$ order tensor 
- Similar to Numpy ndarray with few extra options
- the tensor class supports automatic differentiation
- leverages GPUs to accelerate numerical computation


In [4]:
# Create basic 1d tensor (vector)
x = torch.arange(0, 12, dtype=torch.int64)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
# Get th number of elements in the tensor
x.numel()

12

In [7]:
# Get the shape of the tensor
x.shape

torch.Size([12])

In [12]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
Y = x.reshape(4,3)
Y

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [15]:
Z = x.reshape(3,2,2)
Z

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [16]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
torch.ones(2,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [22]:
R = torch.rand(2,3,4)

In [23]:
R.shape

torch.Size([2, 3, 4])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

torch.Size([2, 3])

In [ ]:
torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
]).shape

torch.Size([1, 3, 3])

In [28]:
torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,20,30],
        [40,50,60],
        [70,80,90]
    ]
]).shape

torch.Size([2, 3, 3])

# Indexing and Slicing

In [31]:
X[0][1]

tensor(1)

In [58]:
rn = torch.rand(4,2,6,)

In [72]:
rn

tensor([[[0.0830, 0.0751, 0.1474, 0.6161, 0.4609, 0.3846],
         [0.7603, 0.8071, 0.8540, 0.9838, 0.5104, 0.0663]],

        [[0.4126, 0.2318, 0.7605, 0.7208, 0.3830, 0.8887],
         [0.7021, 0.7988, 0.2698, 0.2687, 0.7930, 0.7253]],

        [[0.3961, 0.4787, 0.5930, 0.7325, 0.2186, 0.3695],
         [0.1476, 0.0858, 0.7262, 0.4829, 0.5942, 0.2515]],

        [[0.8853, 0.1658, 0.7454, 0.5745, 0.4822, 0.2211],
         [0.7186, 0.5265, 0.1586, 0.9491, 0.1679, 0.8749]]])

In [79]:
rn[2][1][1] = 10

In [77]:
rn[1:2] = 1

In [78]:
rn

tensor([[[0.0830, 0.0751, 0.1474, 0.6161, 0.4609, 0.3846],
         [0.7603, 0.8071, 0.8540, 0.9838, 0.5104, 0.0663]],

        [[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000]],

        [[0.3961, 0.4787, 0.5930, 0.7325, 0.2186, 0.3695],
         [0.1476, 0.0858, 0.7262, 0.4829, 0.5942, 0.2515]],

        [[0.8853, 0.1658, 0.7454, 0.5745, 0.4822, 0.2211],
         [0.7186, 0.5265, 0.1586, 0.9491, 0.1679, 0.8749]]])

In [80]:
rn

tensor([[[ 0.0830,  0.0751,  0.1474,  0.6161,  0.4609,  0.3846],
         [ 0.7603,  0.8071,  0.8540,  0.9838,  0.5104,  0.0663]],

        [[ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000]],

        [[ 0.3961,  0.4787,  0.5930,  0.7325,  0.2186,  0.3695],
         [ 0.1476, 10.0000,  0.7262,  0.4829,  0.5942,  0.2515]],

        [[ 0.8853,  0.1658,  0.7454,  0.5745,  0.4822,  0.2211],
         [ 0.7186,  0.5265,  0.1586,  0.9491,  0.1679,  0.8749]]])

In [91]:
rn[0:1, 1:2, 1:3]

tensor([[[0.8071, 0.8540]]])

# Element wise Operations

In [103]:
a = torch.arange(1, 17,step=1)
b = torch.arange(17, 17 + a.shape[0], step = 1)

In [105]:
b.shape[0] == a.shape[0]

True

In [110]:
# Addtion
print('\n', a, '\n', a+2)


 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]) 
 tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])


In [111]:
# Subtraction
print('\n', a, '\n', a-10)


 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]) 
 tensor([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])


In [113]:
# Multiplication
print('\n', a, '\n', a*10)


 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]) 
 tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
        150, 160])


In [121]:
a*b


tensor([ 17,  36,  57,  80, 105, 132, 161, 192, 225, 260, 297, 336, 377, 420,
        465, 512])

In [120]:
a.mul(b)

tensor([ 17,  36,  57,  80, 105, 132, 161, 192, 225, 260, 297, 336, 377, 420,
        465, 512])

In [119]:
torch.mul(a,b)

tensor([ 17,  36,  57,  80, 105, 132, 161, 192, 225, 260, 297, 336, 377, 420,
        465, 512])

In [123]:
# Division
a/b


tensor([0.0588, 0.1111, 0.1579, 0.2000, 0.2381, 0.2727, 0.3043, 0.3333, 0.3600,
        0.3846, 0.4074, 0.4286, 0.4483, 0.4667, 0.4839, 0.5000])

In [128]:
a.div(b)

tensor([0.0588, 0.1111, 0.1579, 0.2000, 0.2381, 0.2727, 0.3043, 0.3333, 0.3600,
        0.3846, 0.4074, 0.4286, 0.4483, 0.4667, 0.4839, 0.5000])

In [129]:
torch.div(a,b)

tensor([0.0588, 0.1111, 0.1579, 0.2000, 0.2381, 0.2727, 0.3043, 0.3333, 0.3600,
        0.3846, 0.4074, 0.4286, 0.4483, 0.4667, 0.4839, 0.5000])

In [130]:
# Power
a**b

tensor([                   1,               262144,           1162261467,
               1099511627776,      476837158203125,   131621703842267136,
         8922003266371364727,                    0,  6048575297968530377,
        -2537764290115403776,  3409482885583668627,  3530822107858468864,
         3393902732584081725, -2594600101900976128, -8207802330756800273,
                           0])

In [131]:
a.pow(b)

tensor([                   1,               262144,           1162261467,
               1099511627776,      476837158203125,   131621703842267136,
         8922003266371364727,                    0,  6048575297968530377,
        -2537764290115403776,  3409482885583668627,  3530822107858468864,
         3393902732584081725, -2594600101900976128, -8207802330756800273,
                           0])

In [132]:
torch.pow(a,b)

tensor([                   1,               262144,           1162261467,
               1099511627776,      476837158203125,   131621703842267136,
         8922003266371364727,                    0,  6048575297968530377,
        -2537764290115403776,  3409482885583668627,  3530822107858468864,
         3393902732584081725, -2594600101900976128, -8207802330756800273,
                           0])

In [134]:
# Reminder or Modulus
a % 2

tensor([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [135]:
a.remainder(2)

tensor([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [136]:
torch.remainder(a,2)

tensor([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

# Comparision Operators


In [137]:
# Greater
a > 2

tensor([False, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True])

In [138]:
a.greater(2)

tensor([False, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True])

In [139]:
torch.greater(a, 2)

tensor([False, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True])

In [141]:
torch.gt(a, 2)

tensor([False, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True])

In [142]:
torch.greater_equal(a,2)

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True])

In [143]:
torch.ge(a, 2)

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True])

In [140]:
# Less Than
a < 2

tensor([ True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [144]:
a.less(2)

tensor([ True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [145]:
a.lt(2)

tensor([ True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [146]:
torch.lt(a,2)

tensor([ True, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [147]:
torch.le(a,2)

tensor([ True,  True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [ ]:
a == 2 # Elementwise


tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [152]:
a == b

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [153]:
a.eq(b)

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False])

In [154]:
a.equal(b)

False

In [155]:
a != b

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True])

In [156]:
a.ne(b)

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True])

In [158]:
torch.ne(a,b)

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True])

# Logical Operations

In [159]:
logic_a = torch.tensor([True, False, True, False], dtype=torch.bool)
logic_b = torch.tensor([True, False, False, True], dtype=torch.bool)

In [160]:
logic_a.logical_and(logic_b)

tensor([ True, False, False, False])

In [161]:
logic_b.logical_and(logic_a)

tensor([ True, False, False, False])

In [162]:
logic_a.logical_or(logic_b)

tensor([ True, False,  True,  True])

In [163]:
torch.logical_not(logic_a)

tensor([False,  True, False,  True])

In [164]:
torch.logical_xor(logic_b, logic_b)

tensor([False, False, False, False])

# Other Mathematical Operations

In [165]:
x = torch.tensor([-10, -8, 7, 6, 5])

In [166]:
torch.abs(x)

tensor([10,  8,  7,  6,  5])

In [168]:
torch.sqrt(torch.abs(x))

tensor([3.1623, 2.8284, 2.6458, 2.4495, 2.2361])

In [170]:
torch.exp(a)

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02, 4.0343e+02,
        1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05,
        4.4241e+05, 1.2026e+06, 3.2690e+06, 8.8861e+06])

In [171]:
torch.log(a)

tensor([0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794, 2.1972,
        2.3026, 2.3979, 2.4849, 2.5649, 2.6391, 2.7081, 2.7726])

In [173]:
torch.log10(a)

tensor([0.0000, 0.3010, 0.4771, 0.6021, 0.6990, 0.7782, 0.8451, 0.9031, 0.9542,
        1.0000, 1.0414, 1.0792, 1.1139, 1.1461, 1.1761, 1.2041])

In [178]:
torch.ceil(x / 3)

tensor([-3., -2.,  3.,  2.,  2.])

In [179]:
torch.floor(x / 3)

tensor([-4., -3.,  2.,  2.,  1.])

In [183]:
torch.round(x/ 3, decimals=3)

tensor([-3.3330, -2.6670,  2.3330,  2.0000,  1.6670])

In [184]:
torch.sigmoid(a)

tensor([0.7311, 0.8808, 0.9526, 0.9820, 0.9933, 0.9975, 0.9991, 0.9997, 0.9999,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [186]:
torch.relu(torch.tensor([0.05, 0.09]))

tensor([0.0500, 0.0900])

# In-Place Operations

In [191]:
print('before', a)
a.add_(2)
print('after',a)

before tensor([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])
after tensor([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])


In [192]:
print('before', a)
a.sub_(2)
print('after',a)

before tensor([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
after tensor([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])


In [193]:
print('before', a)
a.mul_(2)
print('after',a)

before tensor([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])
after tensor([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44])


In [200]:
print('before', a)
a = a.float()
a.div_(2)
print('after',a)

before tensor([ 3.5000,  4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,
         7.5000,  8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000, 11.0000])
after tensor([1.7500, 2.0000, 2.2500, 2.5000, 2.7500, 3.0000, 3.2500, 3.5000, 3.7500,
        4.0000, 4.2500, 4.5000, 4.7500, 5.0000, 5.2500, 5.5000])


# Trignometric Operations

In [201]:
torch.sin(a)

tensor([ 0.9840,  0.9093,  0.7781,  0.5985,  0.3817,  0.1411, -0.1082, -0.3508,
        -0.5716, -0.7568, -0.8950, -0.9775, -0.9993, -0.9589, -0.8589, -0.7055])

In [202]:
torch.cos(a)

tensor([-0.1782, -0.4161, -0.6282, -0.8011, -0.9243, -0.9900, -0.9941, -0.9365,
        -0.8206, -0.6536, -0.4461, -0.2108,  0.0376,  0.2837,  0.5121,  0.7087])

In [203]:
torch.tan(a)

tensor([ -5.5204,  -2.1850,  -1.2386,  -0.7470,  -0.4129,  -0.1425,   0.1088,
          0.3746,   0.6966,   1.1578,   2.0063,   4.6373, -26.5754,  -3.3805,
         -1.6773,  -0.9956])

# Type casting the Tensors

In [206]:
x = torch.tensor([1, 2, 3])

In [207]:
x.dtype

torch.int64

In [ ]:
# Floating Point Types
float_tensor = x.float()           # Default float (32-bit)
print(float_tensor.dtype)
float32_tensor = x.to(torch.float32)
print(float32_tensor.dtype)
float32_tensor = x.type(torch.float32)
print(float32_tensor.dtype)

torch.float32
torch.float32
torch.float32


In [ ]:
float64_tensor = x.double()          # 64-bit float
float64_tensor = x.to(torch.float64)
float64_tensor = x.type(torch.float64)
print(float64_tensor.dtype)

torch.float64


In [ ]:
float16_tensor = x.half()            # 16-bit float
float16_tensor = x.to(torch.float16)
float16_tensor = x.type(torch.float16)
print(float16_tensor.dtype)

torch.float16


In [213]:
bfloat16_tensor = x.bfloat16()       # Brain floating point format
bfloat16_tensor = x.to(torch.bfloat16)
bfloat16_tensor = x.type(torch.bfloat16)
print(bfloat16_tensor.dtype)

torch.bfloat16


In [215]:
# Integer Types
int32_tensor = x.int()               # 32-bit integer
int32_tensor = x.to(torch.int32)
int32_tensor = x.type(torch.int32)
print(int32_tensor.dtype)

torch.int32


In [216]:
int64_tensor = x.long()              # 64-bit integer
int64_tensor = x.to(torch.int64)
int64_tensor = x.type(torch.int64)
print(int64_tensor.dtype)

torch.int64


In [217]:
int16_tensor = x.short()             # 16-bit integer
int16_tensor = x.to(torch.int16)
int16_tensor = x.type(torch.int16)
print(int16_tensor.dtype)

torch.int16


In [218]:

int8_tensor = x.char()               # 8-bit integer
int8_tensor = x.to(torch.int8)
int8_tensor = x.type(torch.int8)
print(int8_tensor.dtype)

torch.int8


In [219]:

# Unsigned Integer Types
uint8_tensor = x.byte()              # 8-bit unsigned integer
uint8_tensor = x.to(torch.uint8)
uint8_tensor = x.type(torch.uint8)
print(uint8_tensor.dtype)

torch.uint8


In [222]:

# Boolean Type
y = torch.tensor([1,0,0,1])
bool_tensor = y.bool()               # Boolean
bool_tensor = x.to(torch.bool)
bool_tensor = x.type(torch.bool)
print(bool_tensor.dtype)
y

torch.bool


tensor([1, 0, 0, 1])

In [223]:

# Complex Types
complex64_tensor = x.to(torch.complex64)    # Complex number (float32 real and imaginary)
complex128_tensor = x.to(torch.complex128)  # Complex number (float64 real and imaginary)


In [234]:

# Device and dtype casting together
gpu_float_tensor = x.to(device=device, dtype=torch.float32)  # If GPU available
gpu_float_tensor = gpu_float_tensor.to(device='cpu')
gpu_float_tensor

tensor([1., 2., 3.])

In [235]:

# Type checking
dtype = x.dtype                      # Get current dtype
is_floating = x.is_floating_point()  # Check if tensor is floating point
is_complex = x.is_complex()          # Check if tensor is complex


In [ ]:

# Memory format preservation during casting
contiguous_tensor = x.contiguous().to(torch.float32)  # Ensure contiguous memory layout


In [ ]:

# Handling gradients during casting
requires_grad_tensor = x.to(torch.float32, requires_grad=True)

# from and to Numpy conversions 

In [236]:
import numpy as np

# ====== NumPy to PyTorch ======
# Basic conversion
numpy_array = np.array([1, 2, 3])
torch_tensor = torch.from_numpy(numpy_array)                 # Shares memory with numpy array
torch_tensor = torch.tensor(numpy_array)                    # Creates a copy
torch_tensor = torch.as_tensor(numpy_array)                 # Shares memory when possible


In [237]:

# Specify dtype during conversion
torch_float = torch.from_numpy(numpy_array).float()
torch_float = torch.tensor(numpy_array, dtype=torch.float32)
torch_float = torch.as_tensor(numpy_array, dtype=torch.float32)


In [240]:

# Convert and move to GPU (if available)
torch_gpu = torch.from_numpy(numpy_array).to(device=device)
torch_gpu = torch.tensor(numpy_array, device=device)
torch_gpu = torch.as_tensor(numpy_array, device=device)


In [241]:

# Handle special numpy arrays
torch_masked = torch.from_numpy(np.ma.masked_array([1, 2, 3], mask=[0, 1, 0]))
torch_tensor = torch.tensor(np.nan)  # Handle NaN values
torch_tensor = torch.tensor(np.inf)  # Handle infinity


In [242]:

# ====== PyTorch to NumPy ======
# Basic conversion
torch_tensor = torch.tensor([1, 2, 3])
numpy_array = torch_tensor.numpy()                          # Only works for CPU tensors
numpy_array = torch_tensor.detach().numpy()                 # Detach from computation graph first
numpy_array = torch_tensor.cpu().numpy()                    # Move to CPU first if needed


In [244]:

# Handle GPU tensors
gpu_tensor = torch_tensor.to(device=device)
numpy_array = gpu_tensor.cpu().numpy()                      # Must move to CPU first


In [245]:

# Handle gradients
grad_tensor = torch.tensor([1., 2., 3.], requires_grad=True)
numpy_array = grad_tensor.detach().numpy()                  # Detach to remove gradients
numpy_array = grad_tensor.data.numpy()                      # Alternative way to get data


In [246]:

# Special conversions
numpy_array = torch_tensor.numpy(force=True)                # Force numpy conversion
numpy_array = torch_tensor.detach().clone().numpy()         # Create a copy before converting


In [247]:

# ====== Common Pitfalls and Solutions ======
# Handle non-contiguous tensors
non_contiguous = torch_tensor.transpose(0, 1)
numpy_array = non_contiguous.contiguous().numpy()           # Make contiguous first


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [248]:

# Handle different data types
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_numpy = int_tensor.float().numpy()                    # Convert dtype before numpy()


In [249]:

# Preserve gradients information (if needed)
grad_numpy = grad_tensor.grad.numpy() if grad_tensor.grad is not None else None


In [250]:

# ====== Memory Sharing Examples ======
# Check if memory is shared
numpy_array = np.array([1, 2, 3])
torch_shared = torch.from_numpy(numpy_array)
numpy_array[0] = 100  # Changes will be reflected in torch_shared


In [251]:

# Create a copy to avoid sharing
torch_copy = torch.tensor(numpy_array.copy())
numpy_array[0] = 200  # Won't affect torch_copy


In [252]:

# ====== Shape Handling ======
# Preserve dimensions
numpy_2d = np.array([[1, 2], [3, 4]])
torch_2d = torch.from_numpy(numpy_2d)                       # Preserves 2D shape


In [253]:

# Handle different memory layouts
numpy_f = np.array([[1, 2], [3, 4]], order='F')            # Fortran-style array
torch_f = torch.from_numpy(numpy_f)                         # Preserves memory layout